CREATE TABLE IF NOT EXISTS payment_methods (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name  VARCHAR(255) NOT NULL UNIQUE,

    type ENUM(
        'CRYPTO',
        'BANK TRANSFER'
    ) NOT NULL,

    created_at TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP,    

    updated_at TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
        
)  ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;